// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOXAsYVaf9ObNaAKoiq2OzE-hCqFXCds4',
    appId: '1:804771459012:web:3f8487b64fbc05bda47e91',
    messagingSenderId: '804771459012',
    projectId: 'flutter-expense-d4f96',
    authDomain: 'flutter-expense-d4f96.firebaseapp.com',
    storageBucket: 'flutter-expense-d4f96.appspot.com',
    measurementId: 'G-SDP0GH3J1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKP4esBA80tJTkGIEYXdqwzimvpBAFf70',
    appId: '1:804771459012:android:e9e342114dc92e75a47e91',
    messagingSenderId: '804771459012',
    projectId: 'flutter-expense-d4f96',
    storageBucket: 'flutter-expense-d4f96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoyD6Z2uOdvjW-VB4RqH3HGVlkf0d365I',
    appId: '1:804771459012:ios:473840713e3f89c2a47e91',
    messagingSenderId: '804771459012',
    projectId: 'flutter-expense-d4f96',
    storageBucket: 'flutter-expense-d4f96.appspot.com',
    androidClientId: '804771459012-bicflnj5cect49hutva54khnm9kc459m.apps.googleusercontent.com',
    iosClientId: '804771459012-1g4uhnpf7fqrmqhd13qrv4jle8reqq3u.apps.googleusercontent.com',
    iosBundleId: 'com.vm.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoyD6Z2uOdvjW-VB4RqH3HGVlkf0d365I',
    appId: '1:804771459012:ios:095b29c3b52fc7bea47e91',
    messagingSenderId: '804771459012',
    projectId: 'flutter-expense-d4f96',
    storageBucket: 'flutter-expense-d4f96.appspot.com',
    androidClientId: '804771459012-bicflnj5cect49hutva54khnm9kc459m.apps.googleusercontent.com',
    iosClientId: '804771459012-h5vg1rhue2pbi1hr3puado130nuid56e.apps.googleusercontent.com',
    iosBundleId: 'com.vm.expense.RunnerTests',
  );
}
